### ISSUE TITLE
 RequestsHttpConnection is no longer available.

### ISSUE THREAD

**Issue by SWS2nd** [aws-samples/amazon-sagemaker-visual-search#11]
!pip uninstall elasticsearch -y
!pip install elasticsearch==7.13.4

but, still ImportError: cannot import name 'RequestsHttpConnection'

OTL...

**Comment by laithalsaadoon** [comment]
@SWS2nd Hello!

Apologies for the late response. Today I merged a maintenance branch which fixes many errors related to dependency changes. Please give it a try!
